name: test_raidiam

on: [push]

jobs:
  build:
    name: run Raidiam tests
    runs-on: ubuntu-18.04 
    container: 
     image: icebreakerone/statusenv:latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: Run test
        run: |
            bash ./setup_scripts/run-raidiam.sh
